package ie.homelab.mazesolver;

import ie.homelab.mazesolver.model.Maze;
import ie.homelab.mazesolver.view.MazePanel;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/*
 * Copyright (C) 2026 derek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
/**
 * Maze solver frame for graphical Maze Solver output.
 *
 * @author derek
 */
public class MazeSolverFrame extends javax.swing.JFrame {

    private static final Logger LOGGER = Logger.getLogger(MazeSolverFrame.class.getName());
    private static final long serialVersionUID = 1L;
    /**
     * Maze data structure.
     */
    protected static Maze maze;

    /**
     * Creates new form MazeSolverFrame.
     */
    public MazeSolverFrame() {
        initComponents();

        StringBuilder sb = new StringBuilder();

        initMaze(20);

        MazeGenerator mazeGenerator = new MazeGenerator(maze);
        mazeGenerator.generateMaze();
        sb.append(maze);
        sb.append("\n\n");

        MazeResolver resolver = new MazeResolver(maze);
        resolver.resolveMaze();
        sb.append(maze);
        sb.append("Path: ").append(resolver.getPointDistance(maze.getStart()));
        sb.append("\n\n");

        sb.append("-- Ending Maze Solver --\n");

        MazePanel mp = new MazePanel(maze);
        mp.setVisible(true);
        displayPanel.add(mp);
        displayPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new JPanel();
        scrollPane = new JScrollPane();
        displayPanel = new JPanel();
        menuBar = new JMenuBar();
        fileMenu = new JMenu();
        exitMenuItem = new JMenuItem();
        helpMenu = new JMenu();
        aboutMenuItem = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maze Solver");
        setMinimumSize(new Dimension(400, 400));
        setSize(new Dimension(400, 800));

        mainPanel.setMinimumSize(new Dimension(200, 200));
        mainPanel.setPreferredSize(new Dimension(400, 400));

        scrollPane.setMinimumSize(new Dimension(200, 200));
        scrollPane.setViewportView(displayPanel);

        displayPanel.setMinimumSize(new Dimension(200, 200));
        displayPanel.setName(""); // NOI18N

        GroupLayout displayPanelLayout = new GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(displayPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGap(0, 441, Short.MAX_VALUE));
        displayPanelLayout.setVerticalGroup(displayPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGap(0, 512, Short.MAX_VALUE));

        scrollPane.setViewportView(displayPanel);

        GroupLayout mainPanelLayout = new GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGap(0, 488, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addGap(0, 0, Short.MAX_VALUE))));
        mainPanelLayout.setVerticalGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGap(0, 425, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addGap(0, 0, Short.MAX_VALUE))));

        fileMenu.setText("File");

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(this::exitMenuItemActionPerformed);
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE));

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(ActionEvent evt) { // GEN-FIRST:event_exitMenuItemActionPerformed
        if(evt.getActionCommand().equals("Exit")){
            System.exit(0);
        }
    } // GEN-LAST:event_exitMenuItemActionPerformed

    /**
     * MazeSolver frame main method.
     *
     * @param args the command line arguments
     */
    public static void main(final String[] args) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            LOGGER.log(Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> new MazeSolverFrame().setVisible(true));

    }

    /**
     * Initialise maze.
     *
     * @param mazeSize int value in the range MIN_SIZE - MAX_SIZE
     */
    protected static void initMaze(final int mazeSize) {

        maze = new Maze(mazeSize);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JMenuItem aboutMenuItem;
    private JPanel displayPanel;
    private JMenuItem exitMenuItem;
    private JMenu fileMenu;
    private JMenu helpMenu;
    private JPanel mainPanel;
    private JMenuBar menuBar;
    private JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
