package ie.homelab.mazesolver.view;

/*
 * Copyright (C) 2026 derek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

import ie.homelab.mazesolver.model.Maze;
import javax.swing.GroupLayout;
import javax.swing.JPanel;

/**
 * Maze Panel for displaying graphical maze representations.
 *
 * @author derek
 */
public class MazePanel extends JPanel {

    /**
     * Serial Version UID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Maze data.
     */
    private final Maze maze;

    /**
     * Creates new form MazePanel.
     */
    public MazePanel() {
        this.maze = null;
        initComponents();
    }

    /**
     * Creates new form MazePanel.
     *
     * @param mazeInput Maze data.
     */
    public MazePanel(final Maze mazeInput) {
        this.maze = mazeInput;
        initComponents();
        drawMaze();
    }

    /**
     * Draw maze from maze data.
     */
    private void drawMaze() {
        System.out.println(maze);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));
    } // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
